#%RAML 1.0
title: emp-onboard-sapi
description: employe onboarding api
baseUri: https://localhost:8082/emp-sapi/v1
/add-employee:
  post:
    body:
      application/json:
        example:
          {
            "empid": 200,
            "empname": "chollk",
            "status": "Ok"
          } 
    responses:
      200:
        body:
          application/json:
            example:
              {
                "status": 200,
                "message": "Success"
              }
      500:
        body:
            application/json:
              example:
                {
                  "status": 500,
                  "message": "Internal server error"
                }
/update-employee:
  description: to update employee information
  post:
    body:
      application/json:
        example:
          <?xml version="1.0" encoding="UTF-8" ?>
            <emp>
              <empid>100</empid>
              <empstatus>Inactive</empstatus>
            </emp>
    responses:
      200:
        body:
          application/xml:
            example:
              <?xml version="1.0" encoding="UTF-8" ?>
                <response>
                  <status>200</status>
                  <message>server error</message>
                </response>
      500:
        body:
          application/xml:
            example:
              <?xml version="1.0" encoding="UTF-8" ?>
                <response>
                  <status>200</status>
                  <message>server error</message>
                </response>
/fetch-employee:
  get:
    queryParameters:
      empid:
        displayName: empid
        required: true
        type: integer
        example: 8788
      status:
        displayName: status
        required: false
        type: string
        example: "A"
    responses:
      200:
        body:
          application/json:
            example:
              {
                "empid": 200,
                "empname": "chollk",
                "status": "Ok"
              }   
      404:
        body:
          application/json:
            example:
              {
                "status": 404,
                "message": "No Employee found"
              }
      500:
        body:
          application/json:
            example:
              {
                "status": 505,
                "message": "Server Error"
              }
/delete-employee/{empid}:
  description: To delete emplyee
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "empid": 200,
                "empname": "chollk",
                "status": "Ok"
              }
    
      404:
        body:
          application/json:
            example:
              {
                "status": 404,
                "message": "No Employee found"
              }
      500:
        body:
          application/json:
            example:
              {
                "status": 505,
                "message": "Server Error"
              } 
    
        
  
  
                               
            

                                                      
        
                                  

        
        


               
        